export const COLORS_LIST = [
  { label: "Green", value: "#277c78" },
  { label: "Yellow", value: "#f2cdac" },
  { label: "Cyan", value: "#82c9d7" },
  { label: "Navy", value: "#626070" },
  { label: "Red", value: "#c94736" },
  { label: "Purple", value: "#826cb0" },
  { label: "Turquoise", value: "#597c7c" },
  { label: "Brown", value: "#93674f" },
  { label: "Magenta", value: "#934f6f" },
  { label: "Blue", value: "#3f82b2" },
  { label: "Navy Grey", value: "#97a0ac" },
  { label: "Army Green", value: "#7f9161" },
  { label: "Gold", value: "#cab361" },
  { label: "Orange", value: "#be6c49" },
];
